hospital/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *
urlpatterns = [
    path('',Index.as_view(),name='home'),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',SignUp.as_view(),name='signup'),
    path('profile/',profile,name='profile'),
    path('editprofile/',edit_profile,name='editprofile'),
    path('choosedoctor/',ChooseDoctor.as_view(),name='choosedoctor'),
    path('appointment/<int:doctor_id>/',CreateAppointment.as_view(),name='appointment'),
    path('report/<int:patient_id>/',CreateReport.as_view(),name='addreport'),
    path('allreports/<int:patient_id>/',ViewAllReports.as_view(),name='allreports'),
]

hospital_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hospital.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

hospital/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date
from django.utils import timezone
# Create your models here.
class MedUser(AbstractUser):
    Admin = 'AD'
    Doctor = 'DR'
    Patient = 'PT'

    ROLES = (
        (Admin,'Admin'),
        (Doctor,'Doctor'),
        (Patient,'Patient'),
        )
    role = models.CharField(max_length=2, choices=ROLES, default=Patient)

    def __str__(self):
        return self.username

    def full_name(self):
        return self.first_name + " " + self.last_name

class Patient(models.Model):
    user = models.ForeignKey(MedUser, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='patientimage', null=True, blank=True)
    date_of_birth = models.DateField(null=True,blank=True)
    address = models.CharField(null=True,blank=True,max_length=300)

    def __str__(self):
        return self.user.username

    def get_age(self):
        today = date.today()
        return today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))

class Doctor(models.Model):
    user = models.ForeignKey(MedUser, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='doctorimage', null=True, blank=True)
    specialization = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

class Appointment(models.Model):
    morning_slot = 'MS'
    evening_slot = 'ES'
    TIMESLOTS = (
        (morning_slot,'09:00AM-12:00PM'),
        (evening_slot,'01:00PM-04:00PM'),
        )
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    time_slot = models.CharField(max_length=2, choices=TIMESLOTS, default=morning_slot)
    appointment_date = models.DateField(default = timezone.now().date())
    token = models.IntegerField()

    def __str__(self):
        return 'APP'+str(self.id).zfill(4)

class Report(models.Model):
    doctor = models.CharField(max_length=20, default='N/A', null=True, blank=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    details = models.TextField(null=True, blank=True)

    def __str__(self):
        return 'REP'+str(self.id).zfill(4)

hospital/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.utils import timezone
import datetime
from .models import *
from tasks import send_appointment_booking_email

# Create your views here.


class Index(ListView):
    template_name = 'hospital/index.html'
    model = Doctor

    def get_queryset(self):
        return Doctor.objects.all()


class MedUserCreationForm(UserCreationForm):
    class Meta:
        model = MedUser
        fields = UserCreationForm.Meta.fields


class SignUp(CreateView):
    form_class = MedUserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('login')


def profile(request):
    if request.user.role == 'PT':
        patient = Patient.objects.get_or_create(
            user=MedUser.objects.get(id=request.user.id))
        appointments = Appointment.objects.filter(patient=patient[0],
                appointment_date__gte=timezone.now()).order_by('appointment_date')
        patient = patient[0]
        context = {'patient': patient, 'appointments': appointments}
        template_name = 'hospital/patientprofile.html'
    elif(request.user.role == 'DR'):
        doctor = Doctor.objects.get_or_create(
            user=MedUser.objects.get(id=request.user.id))
        forenoon_booking = Appointment.objects.filter(doctor=doctor[0],
                appointment_date=timezone.now(),
                time_slot=Appointment.morning_slot).order_by('appointment_date')
        afternoon_booking = Appointment.objects.filter(doctor=doctor[0],
                appointment_date=timezone.now(),
                time_slot=Appointment.evening_slot).order_by('appointment_date')
        upcoming = Appointment.objects.filter(doctor=doctor[0],
                appointment_date__gt=timezone.now()).order_by('appointment_date')
        doctor = doctor[0]
        context = {'doctor': doctor, 'upcoming': upcoming, 'forenoon_booking': forenoon_booking, 'afternoon_booking': afternoon_booking}
        template_name = 'hospital/doctorprofile.html'
    elif(request.user.role == 'AD'):
        return HttpResponseRedirect('/admin/')
        # admin = MedUser.objects.get(id=request.user.id)
        # context = {'admin': admin}
        # template_name = 'hospital/adminprofile.html'
    else:
        return HttpResponse('admin profile')

    return render(request, template_name, context)


class UserForm(forms.ModelForm):
    class Meta:
        model = MedUser
        fields = ['first_name', 'last_name', 'email']


class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ['specialization', 'photo']


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['photo', 'date_of_birth', 'address']


def edit_profile(request):
    user = MedUser.objects.get(id=request.user.id)
    if request.user.role == 'PT':
        template_name = 'hospital/patienteditprofile.html'
        patient = Patient.objects.get(
            user=MedUser.objects.get(id=request.user.id))
    else:
        template_name = 'hospital/doctoreditprofile.html'
        doctor = Doctor.objects.get(
            user=MedUser.objects.get(id=request.user.id))
    if request.method == 'POST':
        if request.user.role == 'PT':
            form = PatientForm(request.POST, request.FILES, instance=patient)
            userform = UserForm(request.POST, instance=user)
            form.save()
            userform.save()

        if request.user.role=='DR':
            form = DoctorForm(request.POST, request.FILES, instance=doctor)
            userform = UserForm(request.POST, instance=user)
            print(request.FILES)
            form.save()
            userform.save()

        return HttpResponseRedirect('/profile/')

    else:
        userform = UserForm(instance=user)
        if(request.user.role == 'PT'):
            form = PatientForm(instance=patient)

        if(request.user.role == 'DR'):
            form = DoctorForm(instance=doctor)

        context = {'form': form, 'userform': userform}

        return render(request, template_name, context)

class ChooseDoctor(ListView):
    template_name = 'hospital/choosedoctor.html'
    model = Doctor

    def get_queryset(self):
        return Doctor.objects.all()

def get_token(date,doctor):
    appointments = Appointment.objects.filter(appointment_date=date,
                                              doctor=doctor).order_by('-id')
    if appointments:
        return appointments[0].token+1
    else:
        return 1


class AddAppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['time_slot', 'appointment_date']

class CreateAppointment(CreateView):
    model = Appointment
    form_class = AddAppointmentForm
    template_name = 'hospital/appointment.html'
    success_url = reverse_lazy('profile')

    def form_valid(self, form):
        if(self.request.user.is_authenticated):
            patient = Patient.objects.get(user__id=self.request.user.id)
            doctor = Doctor.objects.get(id=self.kwargs.get('doctor_id'))
            self.object = form.save(commit=False)
            self.object.patient = patient
            self.object.doctor = doctor
            self.object.token = get_token(date=self.object.appointment_date,
                                          doctor=self.object.doctor)
            self.object.save()
            send_appointment_booking_email.apply_async([patient.id, doctor.id])
            return super(CreateAppointment, self).form_valid(form)

class AddReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['doctor','details']

class CreateReport(CreateView):
    model = Report
    form_class = AddReportForm
    template_name = 'hospital/createreport.html'
    success_url = reverse_lazy('profile')

    def form_valid(self, form):
        if(self.request.user.is_authenticated):
            patient = Patient.objects.get(id=self.kwargs.get('patient_id'))
            self.object = form.save(commit=False)
            self.object.patient = patient
            self.object.save()
            return super(CreateReport, self).form_valid(form)

class ViewAllReports(ListView):
    template_name = 'hospital/viewallreports.html'
    model = Report

    def get_queryset(self):
        return Report.objects.filter(patient_id=self.kwargs.get('patient_id'))

hospital/templates/hospital/appointment.html
<!DOCTYPE html>
{% load static %}
{% load medextras %}
<html>
<title>Book Appointment</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'style.css' %}">
<style>
.hidden_tab{
  display: none;
}
</style>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", Arial, Helvetica, sans-serif}
</style>
<body class="w3-light-grey">

<!-- Navigation Bar -->
<div class="w3-bar w3-white w3-large">
  <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-red w3-mobile"><i class="fa fa-home w3-margin-right"></i>Hospital</a>
  <a href="{% url 'profile' %}" class="w3-bar-item w3-button w3-mobile">Profile</a>
  <a href="{% url 'choosedoctor' %}" class="w3-bar-item w3-button w3-mobile">Choose Doctors</a>
</div>
<!-- Header -->
<header class="w3-display-container w3-content" style="max-width:1500px;">
  <img class="w3-image" src="{% static 'hospital.jpg' %}" alt="The Hotel" style="min-width:1000px" width="1500" height="800">
  <div class="w3-display-left w3-padding w3-col l6 m8">
    <div class="w3-container w3-red">
      <h2><i class="fa fa-user w3-margin-right"></i>Appointment Booking</h2>
    </div>
    <div class="w3-container w3-white w3-padding-16">
      <form method="post">
        {% csrf_token %}
        <div class="w3-row-padding" style="margin:0 -16px;">
          <div class="w3-half w3-margin-bottom">
            <label for="id_appointment_date"><i class="fa fa-calendar-o"></i> Appointment Date</label>
            {% calculate_date form.appointment_date.value as date %}
            <input class="w3-input w3-border" type="date" id="id_appointment_date" name="appointment_date" value="{{date}}" required>
          </div>
          <div class="w3-half">
            <label for="id_time_slot"><i class="fa fa-clock-o"></i>Time Slot</label>
            <select class="w3-input w3-border" name="time_slot" id="id_time_slot">
              <option value="MS" selected>09:00AM-12:00PM</option>
              <option value="ES">01:00PM-04:00PM</option>
            </select>
        </div>
        </div>
        <button class="w3-button w3-dark-grey" type="submit"><i class="fa fa-check w3-margin-right"></i> Book</button>
      </form>
    </div>
  </div>
</header>

<!-- Page content -->
  <div class="w3-container" id="contact">
    <h2>Contact</h2>
    <p>If you have any questions, do not hesitate to ask them.</p>
    <i class="fa fa-map-marker w3-text-red" style="width:30px"></i> kerala, india<br>
    <i class="fa fa-phone w3-text-red" style="width:30px"></i> Phone:+91 9446352931<br>
    <i class="fa fa-envelope w3-text-red" style="width:30px"> </i> Email: mail@mail.com<br>
    <form action="/action_page.php" target="_blank">
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Name" required name="Name"></p>
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Email" required name="Email"></p>
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Message" required name="Message"></p>
      <p><button class="w3-button w3-black w3-padding-large" type="submit">SEND MESSAGE</button></p>
    </form>
  </div>

<!-- End page content -->
</div>

<!-- Footer -->
<footer class="w3-padding-32 w3-black w3-center w3-margin-top">
  <h5>Find Us On</h5>
  <div class="w3-xlarge w3-padding-16">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
  </div>
  <p>for<a href="https://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">bca project</a></p>
</footer>

</body>
</html>

hospital/templates/hospital/createreport.html
<!DOCTYPE html>
{% load static %}
{% load medextras %}
<html>
<title>Create Report</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'style.css' %}">
<style>
.hidden_tab{
  display: none;
}
</style>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", Arial, Helvetica, sans-serif}
</style>
<body class="w3-light-grey">

<!-- Navigation Bar -->
<div class="w3-bar w3-white w3-large">
  <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-red w3-mobile"><i class="fa fa-home w3-margin-right"></i>Hospital</a>
  <a href="{% url 'profile' %}" class="w3-bar-item w3-button w3-mobile">Profile</a>
</div>
<!-- Header -->
<header class="w3-display-container w3-content" style="max-width:1500px;">
  <img class="w3-image" src="{% static 'hospital.jpg' %}" alt="The Hotel" style="min-width:1000px" width="1500" height="800">
  <div class="w3-display-left w3-padding w3-col l6 m8">
    <div class="w3-container w3-red">
      <h2><i class="fa fa-user w3-margin-right"></i>Report</h2>
    </div>
    <div class="w3-container w3-white w3-padding-16">
      <form method="post">
        {% csrf_token %}
        <div class="w3-row-padding" style="margin:0 -16px;">
          <div class="w3-half w3-margin-bottom">
            <label for="id_doctor"><i class="fa fa-calendar-o"></i> Doctor Name:</label>
            <input type="text" name="doctor" value="N/A" id="id_doctor" maxlength="20">
          </div>
        </div>
        <div class="w3-row-padding" style="margin:0 -16px;">
          <div class="w3-half w3-margin-bottom">
            <label for="id_details">Details:</label>
            <textarea name="details" id="id_details" cols="40" rows="10"></textarea>
        </div>
        </div>
        <button class="w3-button w3-dark-grey" type="submit"><i class="fa fa-check w3-margin-right"></i> Save </button>
      </form>
    </div>
  </div>
</header>

<!-- Page content -->
  <div class="w3-container" id="contact">
    <h2>Contact</h2>
    <p>If you have any questions, do not hesitate to ask them.</p>
    <i class="fa fa-map-marker w3-text-red" style="width:30px"></i> kerala, india<br>
    <i class="fa fa-phone w3-text-red" style="width:30px"></i> Phone:+91 9446352931<br>
    <i class="fa fa-envelope w3-text-red" style="width:30px"> </i> Email: mail@mail.com<br>
    <form action="/action_page.php" target="_blank">
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Name" required name="Name"></p>
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Email" required name="Email"></p>
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Message" required name="Message"></p>
      <p><button class="w3-button w3-black w3-padding-large" type="submit">SEND MESSAGE</button></p>
    </form>
  </div>

<!-- End page content -->
</div>

<!-- Footer -->
<footer class="w3-padding-32 w3-black w3-center w3-margin-top">
  <h5>Find Us On</h5>
  <div class="w3-xlarge w3-padding-16">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
  </div>
  <p>for<a href="https://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">bca project</a></p>
</footer>

</body>
</html>

hospital/templates/hospital/patienteditprofile.html
<!DOCTYPE html>
{% load static %}
{% load medextras %}
<html>
<title>Edit Profile</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'style.css' %}">
<style>
.hidden_tab{
  display: none;
}
</style>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", Arial, Helvetica, sans-serif}
</style>
<body class="w3-light-grey">

<!-- Navigation Bar -->
<div class="w3-bar w3-white w3-large">
  <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-red w3-mobile"><i class="fa fa-home w3-margin-right"></i>Hospital</a>
  <a href="{% url 'profile' %}" class="w3-bar-item w3-button w3-mobile">Profile</a>
</div>
<!-- Header -->
<header class="w3-display-container w3-content" style="max-width:1500px;">
  <img class="w3-image" src="{% static 'hospital.jpg' %}" alt="The Hotel" style="min-width:1000px" width="1500" height="800">
  <div class="w3-display-left w3-padding w3-col l6 m8">
    <div class="w3-container w3-red">
      <h2><i class="fa fa-user w3-margin-right"></i>Edit Profile</h2>
    </div>
    <div class="w3-container w3-white w3-padding-16">
      <form action="{% url 'editprofile' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
          <p class="w3-center">
         {% if form.photo.value %}
            <label>
              <img src="{{form.instance.photo.url}}" class="w3-circle" style="height:106px;width:106px" alt="Avatar">
              <input class="hidden_tab" type="file" name="photo" id="id_photo" value={{form.photo.value}}>
            </label>
	{% else %}
	    <label>
              <img src="{% static 'avatar.jpg' %}" class="w3-circle" style="height:106px;width:106px" alt="Avatar">
              <input class="hidden_tab" type="file" name="photo" id="id_photo" value={{form.photo.value}}>
            </label>
	{% endif %}
          </p>
        <div class="w3-row-padding" style="margin:0 -16px;">
          <div class="w3-half w3-margin-bottom">
            <label for="id_first_name"><i class="fa fa-male"></i> First Name</label>
            <input class="w3-input w3-border" type="text" id="id_first_name" name="first_name" placeholder="John" value="{{userform.first_name.value}}" name="CheckIn" required>
          </div>
          <div class="w3-half">
            <label for="id_last_name"><i class="fa fa-male"></i> Last Name</label>
            <input class="w3-input w3-border" type="text" id="id_last_name" name="last_name" placeholder="Doe" value="{{userform.last_name.value}}" name="CheckOut" required>
          </div>
        </div>
        <div class="w3-row-padding" style="margin:8px -16px;">
          <div class="w3-half w3-margin-bottom">
            <label for="id_email"><i class="fa fa-envelope"></i> Email</label>
            <input class="w3-input w3-border" type="text" id="id_email" name="email" value="{{userform.email.value}}" placeholder="johndoe@gmail.com" required>
          </div>
          <div class="w3-half">
            <label for="id_date_of_birth"><i class="fa fa-calendar-o"></i> D.O.B</label>
            {% calculate_date form.date_of_birth.value as date %}
          <input class="w3-input w3-border" type="date" name="date_of_birth" id="id_date_of_birth" value="{{date}}">
          </div>
        </div>
        <div class="w3-row-padding" style="margin:8px -16px;">
          <div class="w3-half w3-margin-bottom">
            <label for="id_address"><i class="fa fa-address-card-o"></i> Address</label>
            <input class="w3-input w3-border" name="address" type="text" maxlength="300" id="id_address" value="{{form.address.value}}">
          </div>
        </div>
        <button class="w3-button w3-dark-grey" type="submit"><i class="fa fa-check w3-margin-right"></i> Update</button>
      </form>
    </div>
  </div>
</header>

<!-- Page content -->
  <div class="w3-container" id="contact">
    <h2>Contact</h2>
    <p>If you have any questions, do not hesitate to ask them.</p>
    <i class="fa fa-map-marker w3-text-red" style="width:30px"></i> KERALA, INDIA<br>
    <i class="fa fa-phone w3-text-red" style="width:30px"></i> Phone: +91 9446352931<br>
    <i class="fa fa-envelope w3-text-red" style="width:30px"> </i> Email: mail@mail.com<br>
    <form action="/action_page.php" target="_blank">
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Name" required name="Name"></p>
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Email" required name="Email"></p>
      <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Message" required name="Message"></p>
      <p><button class="w3-button w3-black w3-padding-large" type="submit">SEND MESSAGE</button></p>
    </form>
  </div>

<!-- End page content -->
</div>

<!-- Footer -->
<footer class="w3-padding-32 w3-black w3-center w3-margin-top">
  <h5>Find Us On</h5>
  <div class="w3-xlarge w3-padding-16">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
  </div>
  <p>BCA<a href="https://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">PROJECT</a></p>
</footer>

</body>
</html>

hospital/templates/hospital/viewallreports.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<title>Reports</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'style.css' %}">
<link href='https://fonts.googleapis.com/css?family=RobotoDraft' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><style>
html,body,h1,h2,h3,h4,h5 {font-family: "RobotoDraft", "Roboto", sans-serif}
.w3-bar-block .w3-bar-item {padding: 16px}
</style>
<body>

<!-- Side Navigation -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-white w3-animate-left w3-card" style="z-index:3;width:320px;" id="mySidebar">
  <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-border-bottom w3-large"><i class="fa fa-home"></i> HOSPITAL</a>
  <a href="javascript:void(0)" onclick="w3_close()" title="Close Sidemenu"
  class="w3-bar-item w3-button w3-hide-large w3-large">Close <i class="fa fa-remove"></i></a>
  <a href="{% url 'profile' %}" class="w3-bar-item w3-button"><i class="fa fa-inbox w3-margin-right"></i>Profile<i class="fa fa-caret-down w3-margin-left"></i></a>
  <a id="myBtn" onclick="myFunc('Demo1')" href="javascript:void(0)" class="w3-bar-item w3-button"><i class="fa fa-inbox w3-margin-right"></i>Reports<i class="fa fa-caret-down w3-margin-left"></i></a>
  <div id="Demo1" class="w3-hide w3-animate-left">
    {% for report in object_list %}
    <a href="javascript:void(0)" class="w3-bar-item w3-button w3-border-bottom test w3-hover-light-grey" onclick="openMail({{report.id}});w3_close();" id="firstTab">
      <div class="w3-container">
        <h6>Report ID: {{report}}</h6>
        <p>Doctor:{{report.doctor}}</p>
      </div>
    </a>
    {% endfor %}
  </div>
    <a href="{% url 'logout' %}" class="w3-bar-item w3-button"><i class="fa fa-sign-out w3-margin-right"></i>Logout</a>
</nav>

<!-- Overlay effect when opening the side navigation on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="Close Sidemenu" id="myOverlay"></div>

<!-- Page content -->
<div class="w3-main" style="margin-left:320px;">
<i class="fa fa-bars w3-button w3-white w3-hide-large w3-xlarge w3-margin-left w3-margin-top" onclick="w3_open()"></i>
<a href="javascript:void(0)" class="w3-hide-large w3-red w3-button w3-right w3-margin-top w3-margin-right" onclick="document.getElementById('id01').style.display='block'"><i class="fa fa-pencil"></i></a>

{% for report in object_list %}
<div id={{report.id}} class="w3-container person">
  <br>
  <h3>Report:</h3>
  <p>{{report.details}}</p>
</div>
{% endfor %}
</div>

<script>
var openInbox = document.getElementById("myBtn");
openInbox.click();

function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

function myFunc(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
    x.previousElementSibling.className += " w3-red";
  } else {
    x.className = x.className.replace(" w3-show", "");
    x.previousElementSibling.className =
    x.previousElementSibling.className.replace(" w3-red", "");
  }
}

function openMail(personName) {
  var i;
  var x = document.getElementsByClassName("person");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  x = document.getElementsByClassName("test");
  for (i = 0; i < x.length; i++) {
    x[i].className = x[i].className.replace(" w3-light-grey", "");
  }
  document.getElementById(personName).style.display = "block";
  event.currentTarget.className += " w3-light-grey";
}

</script>

<script>
var openTab = document.getElementById("firstTab");
openTab.click();
</script>

</body>
</html>